version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: school_management_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_management
      MYSQL_USER: schooluser
      MYSQL_PASSWORD: schoolpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql
    networks:
      - school_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s

  # Node.js Application
  app:
    build: .
    container_name: school_management_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: schooluser
      DB_PASSWORD: schoolpassword
      DB_NAME: school_management
      DB_PORT: 3306
      PORT: 3000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - school_network
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:

networks:
  school_network:
    driver: bridge
